###############################################################################
# Logsend Configuration
#
# This configuration file monitors container logs for specific keywords and sends 
# notifications when a keyword is found. For certain keywords, an attachment 
# (i.e. the last 50 log lines) is sent along with the notification.
#
# If you are using ntfy you can specify tags and the topic per Container.
#
# Keywords can be plain strings or regex patterns (prefixed with "regex"). 
###############################################################################


containers:
  # -------------------- Media & Entertainment --------------------
  audiobookshelf:
    ntfy_topic: media
    ntfy_tags: "books, headphones"       
    ntfy_priority: "3"
    keywords:
      - "requested download"
      - "downloaded item"
      - regex: 'download (failed|error)'    # Matches "download failed" or "download error"
    keywords_with_attachment:
      - regex: 'critical download error'     # Critical download issues trigger an attachment

  immich_server:
    ntfy_topic: media
    ntfy_tags: "camera, framed_picture"   # Camera and framed picture: image server
    keywords:
      - "upload failed"
      - regex: 'timeout'                     # Timeout errors during upload
    keywords_with_attachment:
      - "error"                             # Any log line containing "error" triggers an attachment

  prowlarr:
    ntfy_topic: media
    ntfy_tags: "mag, satellite"           # Magnifying glass and satellite: indexer monitoring
    keywords:
      - "connection failed"
      - "authentication error"
      - regex: 'error.*(update|connection)'  # Matches errors related to updates or connections
    keywords_with_attachment:
      - regex: 'critical'                    # Critical errors trigger an attachment

  bazarr:
    ntfy_topic: media
    ntfy_tags: "speech_balloon, warning"  # Speech balloon and warning: subtitle errors
    keywords:
      - "download failed"
      - "API error"
      - regex: 'error.*(download|API)'        # Matches errors in download or API calls
    keywords_with_attachment:
      - regex: 'fatal'                       # Fatal errors trigger an attachment

  # -------------------- Books & Documents --------------------
  calibre-web-automated-book-downloader:
    ntfy_topic: books
    ntfy_tags: "books, page_facing_up"    # Books and open page: document processing
    keywords:
      - "book queued"
      - "download successful"
      - regex: 'download (failed|error)'
    keywords_with_attachment:
      - regex: 'critical'                    # Critical failures trigger an attachment

  nextcloud:
    ntfy_topic: documents
    ntfy_tags: "cloud, file_folder"       # Cloud and folder: file sync
    keywords:
      - "sync error"
      - "connection failed"
      - regex: 'database.*error'             # Matches database-related errors
    keywords_with_attachment:
      - regex: 'critical'                    # Critical errors trigger an attachment

  paperless-ngx-webserver-1:
    ntfy_topic: documents
    ntfy_tags: "page_with_curl, memo"      # Document icon and memo: document processing
    keywords:
      - "OCR error"
      - "failed to process document"
      - regex: 'document (failed|error)'     # Generic document processing error
    keywords_with_attachment:
      - regex: 'fatal'                       # Fatal errors trigger an attachment

  # -------------------- Security & Identity --------------------
  crowdsec:
    ntfy_topic: security
    ntfy_tags: "shield, rotating_light"   # Shield and rotating light: security alerts
    keywords:
      - "blocked"
      - regex: 'attack detected'             # Monitors for attack detection messages
    # No attachment for routine security events

  vaultwarden:
    ntfy_topic: identity
    ntfy_tags: "lock, key"                # Lock and key: identity/authentication
    keywords:
      - "Username or password is incorrect"
      - regex: 'incorrect'
      - "username"
      - "password"
    keywords_with_attachment:
      - "password"                          # Critical password issues trigger an attachment

  authentik-server:
    ntfy_topic: identity
    ntfy_tags: "closed_lock_with_key, no_entry_sign"  # Closed lock and no entry: auth errors
    keywords:
      - "login failed"
      - "unauthorized"
      - regex: 'permission denied'
    keywords_with_attachment:
      - regex: 'critical error'             # Critical authentication errors trigger an attachment

  # -------------------- Network & Infrastructure --------------------
  traefik:
    ntfy_topic: network
    ntfy_tags: "globe_with_meridians, warning"  # Globe and warning: network proxy issues
    keywords:
      - "expired"
      - "invalid"
      - regex: 'certificate (has )?expired'  # Matches certificate expiration issues
    keywords_with_attachment:
      - regex: 'fatal'                       # Fatal certificate errors trigger an attachment

  adguardhome:
    ntfy_topic: network
    ntfy_tags: "shield, satellite"        # Shield and satellite: DNS protection
    keywords:
      - "DNS error"
      - "connection timeout"
      - regex: 'query failed'
    keywords_with_attachment:
      - regex: 'critical'                    # Critical DNS issues trigger an attachment

  pihole:
    ntfy_topic: network
    ntfy_tags: "no_entry_sign, mag"       # No entry and magnifying glass: DNS filtering
    keywords:
      - "FTL error"
      - "blocked domain"
      - regex: 'gravity.*failed'              # Catches gravity update failures
    keywords_with_attachment:
      - regex: 'critical'                    # Critical errors trigger an attachment

  unifi-controller:
    ntfy_topic: network
    ntfy_tags: "wifi, antenna_bars"        # WiFi and antenna: wireless network status
    keywords:
      - "disconnected"
      - "AP offline"
      - regex: 'warning.*(disconnected|offline)'  # Warn if access points are offline
    # Routine connectivity warnings do not trigger attachments

  # -------------------- Maintenance & Management --------------------
  portainer:
    ntfy_topic: maintenance
    ntfy_tags: "wrench, gear"             # Wrench and gear: system management
    keywords:
      - "error"
      - "failed to update"
      - regex: '.*(error|failed).*'
    keywords_with_attachment:
      - regex: 'critical'                    # Critical issues trigger an attachment

  syncthing:
    ntfy_topic: maintenance
    ntfy_tags: "arrows_counterclockwise, recycle"  # Refresh arrows and recycle: sync operations
    keywords:
      - "sync error"
      - "failed to connect"
    keywords_with_attachment:
      - regex: 'fatal'                       # Fatal sync errors trigger an attachment

  # -------------------- Monitoring & Visualization --------------------
  grafana:
    ntfy_topic: monitoring
    ntfy_tags: "bar_chart, chart_with_upwards_trend"  # Bar chart and upward trend: monitoring
    keywords:
      - "datasource error"
      - "dashboard failed"
      - regex: 'error.*query'
    keywords_with_attachment:
      - regex: 'fatal'                       # Fatal errors trigger an attachment

  nextcloud-db-1:
    ntfy_topic: documents
    ntfy_tags: "floppy_disk, database"     # Floppy disk and database: DB layer
    keywords:
      - "database connection error"
      - "query failed"
    keywords_with_attachment:
      - regex: 'fatal'                       # Fatal DB errors trigger an attachment

  nextcloud-redis-1:
    ntfy_topic: documents
    ntfy_tags: "zap, electric_plug"        # Zap and electric plug: cache/redis layer
    keywords:
      - "connection refused"
      - "timeout"
    keywords_with_attachment: []              # No attachment for transient cache issues

###############################################################################
# Global Keywords
#
# Global keywords apply to all containers unless overridden by container-specific
# settings. Feel free to remove or tailor these to your needs.
###############################################################################
global_keywords:
  - error
  - segfault
  - panic
  - fatal
  - failed login
  - invalid credentials
  - brute force
  - unauthorized
  - permission denied
  - access denied
  - unhealthy
  - connection refused
  - timeout
  - out of memory

###############################################################################
# Notification Settings (ntfy)
#
# Configure your ntfy notification channel here.
###############################################################################
ntfy:
  url: "http://192.168.178.184:82"   # URL of your ntfy instance
  topic: "logsend"                   # Default topic for notifications (overridden by container-specific topics)
  token: "token"                     # Authentication token (if required)

###############################################################################
# Additional settings for Logsend system.
###############################################################################
settings:
  log-level: INFO                 # Cooldown (in seconds) to avoid sending repeated notifications for the same keyword.
  notification_cooldown: 5
  attachment_lines: 50
  disable_start_message: False
  disable_shutdown_message: False
  disable_restart_message: False

###############################################################################
# End of Configuration
###############################################################################
